import Image from 'next/image';
import Link from 'next/link';
import { cashcast as specimen } from '@/lib/specimens/cashcast';
import type { SpecimenArtwork } from '@/lib/specimens/types';
import SpecimenNavigation from './SpecimenNavigation';
import { CashIcon, ControllerConcept, EngineMap, EvolutionGallery, ForecastLab, GoalLab } from './cashcast/CashCastExperience';
import s from './cashcast/CashCast.module.css';
function Art({art,title,priority=false}:{art:SpecimenArtwork;title:string;priority?:boolean}){return <figure className={s.art}><Image {...art} alt={art.alt} priority={priority} quality={75} sizes="(max-width: 760px) 100vw, 1320px"/><figcaption>{title}<span>Conceptual artwork · imagegen</span></figcaption></figure>;}
function Head({index}:{index:number}){const c=specimen.chapters[index-1];return <header className={s.chapterHead}><span>0{index} / {c.title}</span><h2>{c.heading}</h2>{c.paragraphs.map(p=><p key={p}>{p}</p>)}</header>;}
const manifesto=[['No financial homework','Meaningful income, obligations and a living allowance. The ambition: understand tomorrow without logging every coffee.',0],['Forecasts, not compulsory budgets','Show what may happen on the current path. Leave the person free to choose a different one.',8],['No guilt','No spending grades, broken streaks or moral judgments. When circumstances change, the forecast changes.',3],['Hide the machinery','A clear answer first. Charts, schedules and technical detail only when they help someone understand.',4],['Your decisions remain yours','Inform. Explain. Explore alternatives. Never make the choice on someone else’s behalf.',7]] as const;
const concepts=[['income','Future income','Expected inflows, on a date.'],['commitments','Commitments','Money already promised.'],['buffer','A cash buffer','Room for a changed plan.'],['deadline','Payment deadlines','Timing that cannot be ignored.'],['goal','A goal','A choice with a cash effect.'],['comparison','Two futures','The same start. Different events.'],['recalculation','Recalculation','New assumptions. A new forecast.'],['uncertainty','Uncertainty','An estimate, never a guarantee.']] as const;
function ConceptLanguage(){return <div className={s.concepts}><p className={s.label}>A LANGUAGE FOR TOMORROW / CONCEPTUAL ICONS</p><div>{concepts.map(([id,title,body])=><article key={id}><Image src={`/specimens/cashcast/icons/${id}-v1.webp`} width={384} height={512} alt="" sizes="(max-width: 760px) 40vw, 230px"/><h3>{title}</h3><p>{body}</p></article>)}</div><p className={s.fine}>Original imagegen illustrations. Explanatory concepts, not technical diagrams.</p></div>;}
export default function CashCastFile(){return <main className={s.page}><a className={s.skip} href="#origin">Skip to the financial forecast</a><div className={s.wrap}>
 <header className={s.top}><Link href="/incubation">← GAMA Dynamics / Specimen archive</Link><span>008 / PAUSED — RESEARCH & DEVELOPMENT</span></header>
 <section className={s.hero}><div><p className={s.eyebrow}>CASH CAST / THE UNFINISHED BEGINNING</p><h1>See tomorrow.<br/><em>Change today.</em></h1><p className={s.heroCopy}>The first serious GAMA software project began with a human question.<br/><strong>“Will my money last?”</strong></p><a className={s.cta} href="#origin">Watch a future unfold <span aria-hidden="true">↗</span></a><p className={s.heroNote}>THE FOX. THE BEAST. THE FUTURE.<br/>A paused native project. A philosophy still alive.</p></div><Art art={specimen.artwork.hero} title="The fox sees a little further" priority/></section>
 <SpecimenNavigation chapters={specimen.chapters} className={s.navigation}/>
 <section className={s.chapter} id="origin"><Head index={1}/><div className={s.originLine}><p>$2,000 today.<br/><em>−$350 before payday.</em></p><div><p>The bank balance tells you where you are. Upcoming commitments can reveal where you are heading.</p><strong>What if you saw it coming?</strong><p className={s.fine}>The starting example below is fictional. Every figure follows its event schedule.</p></div></div><ForecastLab/><p className={s.weather}>A financial weather forecast.<br/><span>It tells you rain may be coming.<br/>You decide what to do with that information.</span></p></section>
 <section className={s.chapter} id="experiment"><Head index={2}/><div className={s.rebellion}><blockquote>“I refuse to track<br/>every coffee.”<footer>The founding philosophy</footer></blockquote><div><Image src="/specimens/cashcast/fox-original.png" alt="The original Cash Cast fox, magenta above and cyan below" width={240} height={240}/><p>The fox fights the complexity.<br/><em>Not the user.</em></p></div></div><div className={s.manifesto}>{manifesto.map(([title,body,icon],i)=><article key={title}><span>0{i+1}</span><CashIcon kind={icon}/><div><h3>{title}</h3><p>{body}</p></div></article>)}</div><p className={s.manifestoClose}>YOUR MONEY.<br/>YOUR DECISIONS.<br/><em>YOUR FUTURE.</em></p><p className={s.fine}>A product philosophy, supported by the native help text. It does not claim that every unfinished interface achieved the ideal.</p></section>
 <section className={s.chapter} id="system"><Head index={3}/><Art art={specimen.artwork.paths} title="Different routes. The same right to choose."/><div className={s.goalNarrative}><p>Could tomorrow help you<br/><em>reach a goal today?</em></p><div><p>That question expanded the ambition: available credit, scheduled income, existing obligations, statement timing and full repayment would all have to agree.</p><p>Earlier is a trade-off to understand. A repayment date does not disappear because the purchase happens sooner.</p></div></div><GoalLab/></section>
 <section className={s.chapter} id="problems"><Head index={4}/><Art art={specimen.artwork.beast} title="The beast / A thousand relationships behind an answer"/><div className={s.beastIntro}><p>A question became a model.<br/>The model became <em>a beast.</em></p><div><p>The inspected ChronoFlow source connects recurring entries, cash truth, protected money, goals and credit experiments. The machinery kept growing.</p><p>But more source code is not the same as a validated financial model. Some calculations and interactions remained experimental. That gap belongs in the story.</p></div></div><ConceptLanguage/><EngineMap/><div className={s.truthStrip}><div><span>IMPLEMENTED</span><p>Behaviour authored in the native source. Not a claim of production readiness or financial certification.</p></div><div><span>EXPERIMENTAL</span><p>Designs and calculations explored during development, with unfinished paths and known limitations.</p></div><div><span>VISIONARY</span><p>Future interfaces and possibilities. Clearly presented as concepts, with no relaunch promise.</p></div></div></section>
 <section className={s.chapter} id="solutions"><Head index={5}/><ControllerConcept/><div className={s.evolutionHead}><p className={s.eyebrow}>THE SEARCH FOR SIMPLICITY</p><h3>Every interface<br/>was another question.</h3><p>Conventional dashboards. A familiar mobile home. An airport-style board. An increasingly interconnected command surface. Each direction represented learning.</p></div><EvolutionGallery/>{specimen.captures.length>0&&<div className={s.nativeEvidence}><div><p className={s.eyebrow}>THE ACTUAL APPLICATION / CURRENT SOURCE</p><h3>What survives<br/>in the project.</h3><p>Fresh simulator captures from the retained native working tree. Two compiler compatibility fixes were applied in an isolated copy; its financial logic and interface design were preserved.</p><p className={s.fine}>These captures demonstrate authored views with fictional review data. They are not historical screenshots, a shipped release or evidence of financial correctness.</p></div><div className={s.captures}>{specimen.captures.map(c=><figure key={c.id}><a href={c.src} target="_blank" rel="noreferrer" aria-label={`Open full-size ${c.title}`}><Image src={c.src} alt={c.alt} width={c.width} height={c.height} sizes="(max-width: 700px) 70vw, 350px"/></a><figcaption>{c.title}<small>{c.note}</small></figcaption></figure>)}</div></div>}<p className={s.fine}>No historical screenshot archive was located. The evolution gallery interprets retained source and labels every reconstruction. It never presents imagined screens as implemented screenshots.</p></section>
 <section className={s.chapter} id="evolution"><Head index={6}/><div className={s.unfinished}><span>THE PROJECT THAT STARTED EVERYTHING</span><p>The ambition outran the ability<br/>to keep the whole system clear.</p><div><p>Development paused. The lesson travelled onward: into other applications, stronger engineering practices and a better understanding of what it means to make complexity useful.</p><p>Modern development tools offer new ways to revisit difficult work. They do not establish a return date. CASH CAST remains paused research and development.</p></div></div><Art art={specimen.artwork.final} title="Paused. Not forgotten."/><div className={s.closing}><p className={s.eyebrow}>CASH CAST / SPECIMEN 008</p><h2>See tomorrow.<br/><em>Change today.</em></h2><p>No guilt. No homework.<br/>Just a clearer tomorrow.</p><div><a className={s.cta} href="#origin">Explore another future ↗</a><Link href="/incubation">Return to the specimen archive →</Link></div></div></section>
 <footer className={s.footer}>CASH CAST / PAUSED — RESEARCH & DEVELOPMENT · Source and project history inspected 8 October 2026. Original fox preserved. Cinematic scenes and interface reconstructions are conceptual. Every browser financial value is illustrative.</footer>
 </div></main>;}
