import Link from 'next/link';
import Image from 'next/image';
import { gamaDemo as specimen } from '@/lib/specimens/gama-demo';
import SpecimenNavigation from './SpecimenNavigation';
import DemoExplorer,{ScreenshotComparison} from './flow/DemoExplorer';
import {Artwork,Capture,ChapterHead} from './flow/ExhibitionParts';
import s from './flow/Exhibition.module.css';
export default function DemoFile(){const c=specimen.chapters;return <main className={s.page}>
 <a href="#experiment" className={s.skip}>Skip to the Lobby</a><div className={s.wrap}>
 <header className={s.top}><Link href="/incubation">← GAMA Dynamics / Specimen archive</Link><span className={s.status}>006 / Working native showcase</span></header>
 <section className={s.hero}><p className={s.eyebrow}>GAMA DEMO / A NATIVE PORTFOLIO</p><h1>The portfolio<br/>you can <em>touch.</em></h1><div className={s.heroMeta}><p>One device. Multiple experiences.<br/>The next move belongs to you.</p><span>SWIFTUI / iPHONE + iPAD<br/>LOCAL DEMONSTRATIONS / REAL INTERACTIONS</span><a href="#experiment">Enter the Lobby ↗</a></div><Artwork art={specimen.artwork.hero} title="The gateway / Three worlds within reach" priority/></section>
 <SpecimenNavigation chapters={c} className={s.navigation}/>
 <section id="origin" className={s.chapter}><ChapterHead chapter={c[0]} index={1}/><div className={s.split}><div><p className={s.statement}>You can see the button.<br/><em>What happens when you press it?</em></p><p className={s.prose}>That question is where a conventional portfolio ends. Here, it becomes the starting point.</p><p className={s.fineprint}>A small browser illustration of the difference →</p></div><ScreenshotComparison/></div></section>
 <section id="experiment" className={s.chapter}><ChapterHead chapter={c[1]} index={2}/><div className={s.split}><Capture capture={specimen.captures[0]}/><div><p className={s.eyebrow}>THE ACTUAL APPLICATION</p><p className={s.statement}>Browse.<br/>Choose.<br/><em>Step inside.</em></p><p className={s.prose}>Filter the catalogue by product family and platform. Launch an experience. The host keeps the Lobby separate from each product’s own navigation.</p><p className={s.prose}>The native catalogue can be managed locally: names, order, visibility and artwork. Its platform badges describe each entry; they do not mean the host ships on every listed platform.</p></div></div><div style={{marginTop:60}}><DemoExplorer/></div></section>
 <section id="system" className={s.chapter}><ChapterHead chapter={c[2]} index={3}/><div className={s.captureGrid}>{specimen.captures.slice(1).map((capture,i)=><article key={capture.id}><Capture capture={capture}/><h3>{capture.title}</h3><p>{['Add to the Living List, change quantities, filter shops and explore the pantry. The Martins household is seeded example information.','Discover four shopping entry points. Browse local products, choose sizes, collect picks and build a basket.','Set up the example workflow. Inspect trolleys, replay timestamped history and examine authored insights.'][i]}</p></article>)}</div><div className={s.scope}><h3>A host. An experience. A way back.</h3><p>Launch → retained product root → independent navigation → End Demo confirmation → Lobby.</p><p>The host gives packages a launch context. Coco applies a local persistence namespace; Phoenix’s showcase uses in-memory mock repositories; WAYLINE reads a deterministic event scenario. Returning to the Lobby does not promise universal deletion of local demonstration state.</p></div></section>
 <section id="problems" className={s.chapter}><ChapterHead chapter={c[3]} index={4}/><Artwork art={specimen.artwork.boundary} title="A device-sized world / Separate from live operations"/><div className={s.boundary}><div><strong>INSIDE THE DEMONSTRATION</strong><h3>Touch changes the experience.</h3><div className={s.localNodes}><span>Native views</span><span>Local example state</span><span>Visible feedback</span></div><p>Meaningful interaction with seeded or locally authored information. Each embedded experience owns its own state boundary.</p></div><div className={s.boundaryAside}><strong>OUTSIDE THE DEMONSTRATION</strong><h3>Production stays separate.</h3><p>A local basket is not a live order. A demo trolley is not a machine command. The showcase compositions do not connect these flows to production operations.</p></div></div><div className={`${s.generatedIcons} ${s.demoIcons}`}>{[['Interactive','Your actions change local state.'],['Mocked data','Example information carries the story.'],['Separate production','The demonstration does not operate the live business.'],['Device-native','SwiftUI experiences on iPhone and iPad.'],['Independent roots','Each product retains its own navigation.']].map(([title,body],i)=><figure key={title}><Image src={`/specimens/gama-demo/icons/${i+1}.webp`} width={366} height={570} alt={`${title} — original sculptural concept icon`} sizes="(max-width:650px) 45vw, 18vw"/><figcaption><strong>{title}</strong><p>{body}</p></figcaption></figure>)}</div><p className={s.fineprint}>Original imagegen concept icons. Their explanations describe verified demonstration boundaries.</p></section>
 <section id="solutions" className={s.chapter}><ChapterHead chapter={c[4]} index={5}/><div className={s.split}><div><p className={s.statement}>The portfolio holds them together.<br/><em>The products stay themselves.</em></p><p className={s.prose}>Coco’s warm retail experience. Phoenix’s household rhythm. WAYLINE’s factory view. A shared entrance makes them discoverable without flattening their differences.</p><p className={s.prose}>WAYLINE is an iPad landscape experience. Coco and Phoenix are registered for iPhone and iPad. Six other catalogue entries currently open explicit placeholders.</p></div><Capture capture={specimen.captures[2]}/></div><div className={s.scope}><h3>Selected behaviour, honestly scoped.</h3><p>Embedded demonstrations do not automatically include bundle-specific production capabilities such as widgets, push notifications or purchases. Mock sign-in is not real authentication. Native app source and captured behaviour determine what is claimed here.</p></div></section>
 <section id="evolution" className={s.closing}><p className={s.eyebrow}>CHAPTER 06 / EXPERIENCE THE POSSIBILITIES</p><h2>Don’t just look at<br/>what we’ve built.<br/><span style={{color:'var(--signal)'}}>Experience it.</span></h2><p>GAMA DEMO is a working native showcase. Public App Store or TestFlight distribution has not been verified, so this specimen offers exploration without an invented download promise.</p><Artwork art={specimen.artwork.hero} title="One device / Room for new worlds"/><Link href="#experiment" className={s.cta}>Explore the browser companion ↗</Link><Link href="/incubation/wayline">Continue into WAYLINE →</Link></section>
 <footer className={s.footer}>GAMA DEMO / SPECIMEN 006 · Native source and simulator captures reviewed 8 October 2026. Conceptual artwork is labelled. Browser excerpts are interpretations of selected behaviour.</footer>
 </div></main>;}
