import Link from 'next/link';
import Image from 'next/image';
import { wayline as specimen } from '@/lib/specimens/wayline';
import { defaultStages } from '@/lib/wayline/model';
import SpecimenNavigation from './SpecimenNavigation';
import FactorySimulation from './flow/FactorySimulation';
import { Artwork,Capture,ChapterHead } from './flow/ExhibitionParts';
import s from './flow/Exhibition.module.css';
const future=[['Historical playback','Revisit a production shift through item journeys and station history. The native demo already offers scripted replay; real recorded production playback remains a future integration.'],['Predictive warnings','Explore whether developing queues could reveal tomorrow’s constraints earlier. A vision for investigation, not a deployed prediction engine.'],['Capacity scenarios','Ask what a different admission capacity or service time might change. The browser model provides an illustrative first experiment.'],['Scenario comparisons','Compare the assumptions and outcomes of alternative workflows, with clear conditions rather than a promised productivity gain.'],['Intelligent analysis','Surface patterns in process history while keeping association distinct from causation. Current native insights are authored examples.'],['Multiple lines','Imagine an operational overview spanning several connected lines. The current browser simulation models one finite illustrative line.']];
export default function WaylineFile(){const c=specimen.chapters;return <main className={`${s.page} ${s.wayline}`}><a href="#problems" className={s.skip}>Skip to the interactive factory</a><div className={s.wrap}>
 <header className={s.top}><Link href="/incubation">← GAMA Dynamics / Specimen archive</Link><span className={s.status}>007 / Prototype + future vision</span></header>
 <section className={s.hero}><p className={s.eyebrow}>WAYLINE / INDUSTRIAL FLOW INTELLIGENCE</p><h1>Every item.<br/>Every stage.<br/><em>Every second.</em></h1><div className={s.heroMeta}><p>A factory is a journey through time.<br/>Make every part of it visible.</p><span>EXISTING iPAD DEMO / FUTURE-FACING VISION<br/>CONCEPTUAL BROWSER SIMULATION</span><a href="#problems">Run the factory ↗</a></div><Artwork art={specimen.artwork.hero} title="The Swiss watch / A rhythm to aspire to" priority/></section>
 <SpecimenNavigation chapters={c} className={s.navigation}/>
 <section id="origin" className={s.chapter}><ChapterHead chapter={c[0]} index={1}/><div className={s.split}><p className={s.statement}>The gears have no breaks.<br/><em>People do.</em></p><div><p className={s.prose}>Machines need maintenance. Material arrives late. Processing times vary. One interruption can change the pace of everything downstream.</p><div className={s.watchDiagram}><svg viewBox="0 0 100 100" aria-hidden="true"><g className={s.gear}><circle cx="50" cy="50" r="31"/><circle cx="50" cy="50" r="10"/>{Array.from({length:12},(_,i)=><path key={i} d="M47 9h6v10h-6z" transform={`rotate(${i*30} 50 50)`}/>)}</g></svg><p>Precision is the aspiration.<br/>Visibility helps you understand the reality.</p></div></div></div></section>
 <section id="experiment" className={s.chapter}><ChapterHead chapter={c[1]} index={2}/><div className={s.timeline} aria-label="Conceptual eight-stage item journey">{defaultStages.map((stage,i)=><div key={stage.id}><span>{String(i+1).padStart(2,'0')} →</span><h3>{stage.name}</h3><small>{stage.kind==='buffer'?'WAITING BUFFER':'ACTIVE PROCESS'}</small></div>)}</div><div className={s.split}><Capture capture={specimen.captures[0]}/><div><p className={s.eyebrow}>WHERE THE IDEA ALREADY LIVES</p><p className={s.statement}>A trolley.<br/>A timestamp.<br/><em>A traceable journey.</em></p><p className={s.prose}>The native prototype follows numbered trolleys through six stages: Picking, Racking, Washing, Coating, De-racking and Finishing. Each stage separates PRE, ACTIVE and POST.</p><p className={s.prose}>Journeys, returns, replay and authored insights already express the idea. The eight-stage browser line below develops that thinking into a new conceptual model.</p><p className={s.fineprint}>Authentic interface / deterministic local scenario / no live factory connection</p></div></div></section>
 <section id="system" className={s.chapter}><ChapterHead chapter={c[2]} index={3}/><Artwork art={specimen.artwork.pills} title="Living production pills / An item’s wait becomes visible"/><div className={s.duration}><div><span>ACTIVE PROCESSING</span><h3>Work is happening.</h3><p>The item occupies a station slot. Its processing timer measures time spent in that operation.</p></div><div><span>WAITING</span><h3>The journey continues.</h3><p>The item is queued or dwelling in a waiting buffer. Its clock continues even when processing stops.</p></div></div><div className={s.signalLegend} aria-label="Illustrative waiting thresholds">{[['Normal','Under 20s','#9ce5ed'],['Attention','20s and above','#efcc84'],['Delayed','40s and above','#ffad7b'],['Critical','60s and above','#ff9e9e']].map(([name,time,color])=><div style={{color}} key={name}>{name}<small>{time}</small></div>)}</div><p className={s.fineprint}>These are the simulation’s initial settings. Change the thresholds inside the factory. Colour always travels with readable status text.</p><div className={s.generatedIcons}>{['Processing','Waiting','Queue order','Capacity','Throughput','Elapsed time','Delay','Flow'].map((name,i)=><figure key={name}><Image src={`/specimens/wayline/icons/${i+1}.webp`} alt={`Conceptual ${name.toLowerCase()} icon`} width={384} height={512}/><figcaption>{name}</figcaption></figure>)}</div><p className={s.fineprint}>Original imagegen concept icons / titanium, cyan and amber signal language</p><code className={s.formula}>Flow efficiency = active processing time ÷ total journey time × 100</code><p className={s.prose}>A simple partition, calculated from the item’s history. In this model, journey time equals active processing plus waiting; transfers are instantaneous. It measures simulated flow, not the value of the work or an improvement claim.</p></section>
 <section id="problems" className={s.chapter}><ChapterHead chapter={c[3]} index={4}/><p className={s.prose}>Start the flow, then slow the selected process. PVD coating is selected initially. Accelerate time to see the queue develop. Restore flow and follow the items through to completion.</p><FactorySimulation/></section>
 <section id="solutions" className={s.chapter}><ChapterHead chapter={c[4]} index={5}/><Artwork art={specimen.artwork.manager} title="The manager’s iPad / A conceptual view of the future"/><div className={s.split}><div><p className={s.statement}>Item.<br/>Station.<br/><em>Whole factory.</em></p><p className={s.prose}>Move from one capsule’s history to a station’s workload, then to the operation’s entire journey map. The standalone browser dashboard uses the same simulation model and gives the factory more room.</p><Link className={s.cta} href="/incubation/wayline/manager">Open the manager dashboard ↗</Link></div><div className={s.scope}><h3>Visibility before certainty.</h3><p>A queue is a signal to investigate. It does not establish why a station slowed or prescribe what people should do.</p><p>The generated tablet is a future interface study. The working browser dashboard shows computed simulated data. Neither connects to production equipment, telemetry or real operational records.</p></div></div></section>
 <section id="evolution" className={s.chapter}><ChapterHead chapter={c[5]} index={6}/><p className={s.eyebrow}>FUTURE CONCEPTS / NOT DEPLOYED PRODUCT PROMISES</p><div className={s.future}>{future.map(([title,body],i)=><article key={title}><span>HORIZON {String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className={s.closing}><p className={s.eyebrow}>WAYLINE / SPECIMEN 007</p><h2>Your factory knows<br/>how to produce.<br/><span style={{color:'var(--signal)'}}>WAYLINE shows you<br/>where time disappears.</span></h2><p>An evolving product, a working prototype and a carefully labelled vision of what comes next.</p><Link href="#problems" className={s.cta}>Explore the flow again ↗</Link><Link href="/incubation">Return to the specimen archive →</Link></div></section>
 <footer className={s.footer}>WAYLINE / SPECIMEN 007 · Native prototype inspected 8 October 2026. Generated scenes and future interfaces are conceptual. All browser factory values are simulated.</footer>
 </div></main>;}
