'use client';
import { useEffect, useMemo, useState } from 'react';
import Image from 'next/image';
import { addGoal, addIncome, addUnexpectedExpense, balanceAtDay, compareFutures, compareGoalPaths, createScenario, defaultGoalTerms, forecast, formatDay, formatMoney, movePayment, SAME_DAY_POLICY, type CashForecast } from '@/lib/cashcast/model';
import s from './CashCast.module.css';

const baseline=createScenario();
const money=formatMoney;
type Action='move'|'income'|'expense'|'goal'|null;
function Horizon({result,original,day}:{result:CashForecast;original?:CashForecast;day:number}){
 const values=[...result.days.map(d=>d.closingCents),...result.entries.map(e=>e.balanceCents),...(original?.days.map(d=>d.closingCents)??[]),...(original?.entries.map(e=>e.balanceCents)??[]),0];
 const low=Math.min(...values)-25000,high=Math.max(...values)+25000;
 const x=(d:number)=>20+d/(result.days.length-1)*760;
 const y=(c:number)=>190-(c-low)/(high-low)*166;
 const path=(r:CashForecast)=>r.days.map((d,i)=>`${i?'L':'M'}${x(d.day).toFixed(2)},${y(d.closingCents).toFixed(2)}`).join(' ');
 return <svg className={s.horizon} viewBox="0 0 800 220" role="img" aria-label={`Illustrative daily closing balances. Lowest projected point ${money(result.lowestPoint.balanceCents)} on ${formatDay(result.lowestPoint.day)}. A dashed line, when shown, is the original forecast.`}>
  <line x1="20" x2="780" y1={y(0)} y2={y(0)} stroke="currentColor" strokeDasharray="3 6" opacity=".35"/><text x="22" y={y(0)-8} fill="currentColor" fontSize="12">$0</text>
  {original&&<path d={path(original)} fill="none" stroke="#d898e7" strokeWidth="2" strokeDasharray="5 7" opacity=".7"/>}
  <path d={path(result)} fill="none" stroke="#73e4e9" strokeWidth="3" strokeLinejoin="round"/>
  {result.entries.map(e=><circle key={e.id} cx={x(e.day)} cy={y(e.balanceCents)} r="3.5" fill={e.balanceCents<0?'#f6bc8a':'#73e4e9'}/>)}
  <line x1={x(day)} x2={x(day)} y1="16" y2="199" stroke="#e2c9ed" opacity=".5"/>
  <circle cx={x(day)} cy={y(balanceAtDay(result,day))} r="6" fill={balanceAtDay(result,day)<0?'#f6bc8a':'#f5edf7'}/>
  <text x="20" y="218" fill="currentColor" fontSize="12">{formatDay(0)}</text><text x="780" y="218" textAnchor="end" fill="currentColor" fontSize="12">{formatDay(result.days.length-1)}</text>
 </svg>;
}
export function ForecastLab(){
 const [scenario,setScenario]=useState(createScenario);
 const [day,setDay]=useState(0),[playing,setPlaying]=useState(false),[action,setAction]=useState<Action>(null),[compare,setCompare]=useState(false);
 const [payment,setPayment]=useState('rent-01'),[moveDay,setMoveDay]=useState(15),[amount,setAmount]=useState(50000),[eventDay,setEventDay]=useState(10),[message,setMessage]=useState('A positive balance today. A possible shortfall ahead.');
 const result=useMemo(()=>forecast(scenario,day),[scenario,day]);
 const comparison=useMemo(()=>compareFutures(baseline,scenario),[scenario]);
 const current=balanceAtDay(result,day),event=result.entries.filter(e=>e.day===day);
 useEffect(()=>{if(!playing||day>=scenario.horizonDays)return;const timer=window.setInterval(()=>{if(document.hidden)return;setDay(d=>Math.min(d+1,scenario.horizonDays));},420);return()=>window.clearInterval(timer);},[playing,scenario.horizonDays,day]);
 const showAction=(next:Action)=>{setAction(next);setPlaying(false);if(next==='income'){setAmount(50000);setEventDay(10);}if(next==='expense'){setAmount(45000);setEventDay(9);}if(next==='goal'){setAmount(200000);setEventDay(16);}};
 function apply(){
  if(action==='move'){setScenario(v=>movePayment(v,payment,moveDay));setMessage(`${payment==='rent-01'?'Rent':'Utilities'} moved to ${formatDay(moveDay)} within this example’s agreed window.`);}
  else if(action==='income'){setScenario(v=>addIncome(v,amount,eventDay));setMessage(`${money(amount)} hypothetical income added on ${formatDay(eventDay)}.`);}
  else if(action==='expense'){setScenario(v=>addUnexpectedExpense(v,amount,eventDay));setMessage(`${money(amount)} unexpected expense added on ${formatDay(eventDay)}.`);}
  else if(action==='goal'){setScenario(v=>addGoal(v,amount,eventDay));setMessage(`${money(amount)} cash goal added on ${formatDay(eventDay)}. Its effect is now in the forecast.`);}
  setAction(null);setDay(11);
 }
 function reset(){setScenario(createScenario());setDay(0);setPlaying(false);setAction(null);setCompare(false);setMessage('Original mock forecast restored.');}
 return <div className={s.lab} aria-label="Interactive illustrative cash forecast">
  <div className={s.labTop}><span>THE FINANCIAL HORIZON</span><span>Mock AUD · 4 May – 8 June 2030</span></div>
  <div className={s.labLead}><div><p className={s.label}>TODAY / {formatDay(0)}</p><strong>{money(scenario.openingBalanceCents)}</strong><p>Available at the start. The future is still unfolding.</p></div><div className={s.attention}><span>{result.firstShortfall?'ATTENTION / PROJECTED SHORTFALL':'ATTENTION / THIS SCENARIO'}</span><p>{result.firstShortfall?<>{money(result.firstShortfall.balanceCents)} on {formatDay(result.firstShortfall.day)}<small>After {result.firstShortfall.description.toLowerCase()}. A signal to explore.</small></>:<>No shortfall in these 35 days.<small>Based on the events and assumptions shown.</small></>}</p></div></div>
  <div className={s.forecastMeta}><div><span>COMING UP / FROM {formatDay(day)}</span><strong>{result.nextEvent?`${result.nextEvent.description} · ${formatDay(result.nextEvent.day)}`:'End of this forecast'}</strong><small>{result.nextEvent?`${result.nextEvent.direction==='income'?'+':'−'}${money(result.nextEvent.amountCents)}`:'Events beyond the horizon are not included.'}</small></div><div><span>LOWEST POINT / WHOLE HORIZON</span><strong>{money(result.lowestPoint.balanceCents)}</strong><small>{formatDay(result.lowestPoint.day)} · {result.lowestPoint.description}</small></div></div>
  <div className={s.horizonPanel}><div className={s.cursorBalance}><div><span>PROJECTED / {formatDay(day)}</span><strong data-negative={current<0}>{money(current)}</strong></div><button type="button" onClick={()=>{if(day===scenario.horizonDays||!playing){setDay(0);setPlaying(true);}else setPlaying(false);}}>{playing&&day<scenario.horizonDays?'Pause unfolding':'Watch the forecast'} <span aria-hidden="true">{playing&&day<scenario.horizonDays?'Ⅱ':'↗'}</span></button></div><Horizon result={result} original={compare?comparison.baseline:undefined} day={day}/><label className={s.rangeLabel}>Explore a day<input aria-label="Explore forecast day" type="range" min="0" max={scenario.horizonDays} value={day} onChange={e=>{setDay(Number(e.target.value));setPlaying(false);}}/></label><p className={s.dayDetail}>{event.length?event.map(e=>`${e.description}: ${e.direction==='income'?'+':'−'}${money(e.amountCents)}`).join(' · '):'No scheduled event on this day. The last projected balance carries forward.'}</p>{compare&&<p className={s.key}>Cyan / alternative · Dashed magenta / original · Daily closing balances</p>}</div>
  <div className={s.whatIf}><p className={s.label}>WHAT IF? / CHANGE THE ASSUMPTION. SEE THE EFFECT.</p><div className={s.actions}><button aria-pressed={action==='move'} onClick={()=>showAction('move')}>Move a payment</button><button aria-pressed={action==='income'} onClick={()=>showAction('income')}>Add income</button><button aria-pressed={action==='expense'} onClick={()=>showAction('expense')}>Unexpected expense</button><button aria-pressed={action==='goal'} onClick={()=>showAction('goal')}>Explore a goal</button><button aria-pressed={compare} onClick={()=>setCompare(v=>!v)}>Compare futures</button><button onClick={reset}>Reset</button></div></div>
  {action&&<div className={s.actionPanel}>
   <h4>{action==='move'?'An agreed change in timing.':action==='income'?'A hypothetical income.':action==='expense'?'Life changed. Recalculate.':'A purchase on your horizon.'}</h4>
   {action==='move'?<><label>Eligible mock payment<select value={payment} onChange={e=>{setPayment(e.target.value);setMoveDay(e.target.value==='rent-01'?15:12);}}><option value="rent-01">Rent · {money(120000)}</option><option value="utilities-01">Utilities · {money(18000)}</option></select></label><label>Agreed payment date<select value={moveDay} onChange={e=>setMoveDay(Number(e.target.value))}>{(payment==='rent-01'?[4,11,15,18]:[8,12,16]).map(d=><option key={d} value={d}>{formatDay(d)}</option>)}</select></label><p>This fictional payee permits the displayed dates, with no fee. A real obligation needs an agreement. Card deadlines remain fixed.</p></>:<><label>Illustrative amount<select value={amount} onChange={e=>setAmount(Number(e.target.value))}>{(action==='goal'?[100000,200000,250000]:action==='income'?[25000,50000,100000]:[25000,45000,80000]).map(a=><option value={a} key={a}>{money(a)}</option>)}</select></label><label>Mock event date<select value={eventDay} onChange={e=>setEventDay(Number(e.target.value))}>{(action==='goal'?[16,21,28]:action==='income'?[10,14,21]:[9,18,30]).map(d=><option value={d} key={d}>{formatDay(d)}</option>)}</select></label><p>{action==='goal'?'This adds a cash purchase. The separate two-path experiment below explores hypothetical card timing.':'Presets keep this example fictional. No personal financial information is needed.'}</p></>}
   <div className={s.actions}><button className={s.primary} onClick={apply}>Recalculate this future ↗</button><button onClick={()=>setAction(null)}>Close</button></div>
  </div>}
  <p className={s.liveMessage} role="status">{message}</p>
  {compare&&<div className={s.comparison}><h4>Same starting point. Different events.</h4><table><caption>Original and alternative 35-day forecasts</caption><thead><tr><th scope="col">Projected outcome</th><th scope="col">Original</th><th scope="col">Alternative</th></tr></thead><tbody><tr><th scope="row">Lowest balance</th><td>{money(comparison.baseline.lowestPoint.balanceCents)}</td><td>{money(result.lowestPoint.balanceCents)}</td></tr><tr><th scope="row">First shortfall</th><td>{formatDay(comparison.baseline.firstShortfall!.day)}</td><td>{result.firstShortfall?formatDay(result.firstShortfall.day):'None in horizon'}</td></tr><tr><th scope="row">Closing balance</th><td>{money(comparison.baseline.endBalanceCents)}</td><td>{money(result.endBalanceCents)}</td></tr></tbody></table><p>{comparison.unchanged?'These futures currently match. Change an event to explore an alternative.':`The lowest point changes by ${money(comparison.lowestDeltaCents)}. Timing can change a shortfall without changing the closing balance.`}</p></div>}
  <details className={s.details}><summary>Events & assumptions behind this answer</summary><p>Illustrative estimates, not advice or a prediction of actual cash availability. This browser model is independent of the paused native engine. All amounts are AUD; dates are fictional. Living allowances stand in for everyday spending. No overdraft, interest, tax or inflation is calculated. {SAME_DAY_POLICY} Settlement timing may differ. A 35-day horizon cannot establish longer-term affordability.</p><table><caption>Every event used in this forecast</caption><thead><tr><th scope="col">Date</th><th scope="col">Event</th><th scope="col">Change</th><th scope="col">Balance after</th></tr></thead><tbody>{result.entries.map(e=><tr key={e.id}><td>{formatDay(e.day)}</td><th scope="row">{e.description}<small>{e.id}</small></th><td>{e.direction==='income'?'+':'−'}{money(e.amountCents)}</td><td>{money(e.balanceCents)}</td></tr>)}</tbody></table></details>
 </div>;
}

const goalBase=movePayment(createScenario(),'rent-01',15);
export function GoalLab(){
 const [stress,setStress]=useState(false),[cost,setCost]=useState(200000),[qualifying,setQualifying]=useState(true),[priorPaid,setPriorPaid]=useState(true);
 const paths=useMemo(()=>compareGoalPaths(goalBase,{...defaultGoalTerms,goalCostCents:cost,qualifyingPurchase:qualifying,priorStatementsPaidInFull:priorPaid}),[cost,qualifying,priorPaid]);
 const wait=stress?paths.wait.stressForecast:paths.wait.forecast,acc=stress?paths.accelerate.stressForecast:paths.accelerate.forecast;
 const outcome=stress?paths.accelerate.stressOutcome:paths.accelerate;
 return <div className={s.goalLab} aria-label="Hypothetical cash and credit goal comparison"><div className={s.labTop}><span>TWO PATHS / ONE MOCK GOAL</span><span>Scenario planning · not financial advice</span></div><p className={s.goalIntro}>A separate example begins with rent already agreed for {formatDay(15)}. That resolves the earlier shortfall. Now ask what bringing a purchase forward would change.</p><div className={s.goalControls}><label>Illustrative goal cost<select value={cost} onChange={e=>setCost(Number(e.target.value))}>{[100000,200000,250000].map(v=><option key={v} value={v}>{money(v)}</option>)}</select></label><button aria-pressed={stress} onClick={()=>setStress(v=>!v)}>{stress?'Return to expected timing':'Test late salary + surprise cost'}</button></div>{stress&&<p role="status" className={s.stress}>The second salary now arrives seven days later, on {formatDay(35)}, and an $800 expense appears on {formatDay(30)}. Both original plans stay fixed.</p>}
  <div className={s.paths}><article><span>PATH A / WAIT</span><h3>Let cash catch up.</h3><strong>{paths.wait.purchaseDay===null?'Beyond this horizon':formatDay(paths.wait.purchaseDay)}</strong><p>Earliest cash purchase retaining a $300 buffer through the remaining forecast, under the original assumptions.</p><dl><div><dt>Credit commitment</dt><dd>None for this goal</dd></div><div><dt>Lowest projected cash / whole horizon</dt><dd>{money(wait.lowestPoint.balanceCents)}</dd></div><div><dt>$300 buffer after the planned purchase</dt><dd>{(stress?paths.wait.stressBufferPreserved:paths.wait.bufferPreserved)?'Retained in this model':'Not retained in this model'}</dd></div></dl>{stress&&<p className={s.pathNote}>With the changed assumptions, a newly calculated cash purchase date is {paths.wait.stressReplannedPurchaseDay===null?'beyond the horizon':formatDay(paths.wait.stressReplannedPurchaseDay)}. The original date above stays visible for comparison.</p>}</article>
  <article><span>PATH B / ACCELERATE</span><h3>Bring the purchase forward.</h3><strong>{paths.eligibility.eligible?formatDay(paths.accelerate.purchaseDay!):'Conditions not met'}</strong><p>{paths.eligibility.eligible?`A qualifying purchase creates a full ${money(paths.accelerate.repaymentCents)} repayment, including the $10 example fee, on ${formatDay(paths.accelerate.repaymentDay)}.`:'The arrangement is blocked in this model; no borrowing is added.'}</p>{paths.eligibility.eligible?<dl><div><dt>Full repayment funded at its deadline</dt><dd>{outcome.repaymentCovered?'Yes, under these assumptions':'No — projected cash is insufficient'}</dd></div><div><dt>Lowest projected cash / whole horizon</dt><dd>{money(acc.lowestPoint.balanceCents)}</dd></div><div><dt>$300 buffer through the journey</dt><dd>{outcome.bufferPreserved?'Retained in this model':'Not retained in this model'}</dd></div><div><dt>Stated interest-free conditions</dt><dd>{outcome.interestFreeConditionsMet?'Met in this hypothetical model':'Not met in this hypothetical model'}</dd></div></dl>:<ul>{paths.eligibility.reasons.map(p=><li key={p}>{p}</li>)}</ul>}<p className={s.pathNote}>Earlier access adds a dated obligation. If conditions fail, interest or fees may apply. Their amounts cannot be inferred from these fictional terms.</p></article></div>
  <details className={s.details}><summary>The exact hypothetical card conditions</summary><p>Qualifying retail purchase on {formatDay(2)}; statement closes {formatDay(21)}; full goal purchase plus a $10 fee due {formatDay(33)}. Available credit is $2,500 after existing balances. The prior statement on this same card is the $770 obligation on {formatDay(11)}; the $350 later obligation is another card. Both remain in cash-flow calculations. No cash advance, balance transfer, promotional plan or universal interest-free period is assumed.</p><label className={s.check}><input type="checkbox" checked={qualifying} onChange={e=>setQualifying(e.target.checked)}/>Assume the purchase qualifies under these fictional terms</label><label className={s.check}><input type="checkbox" checked={priorPaid} onChange={e=>setPriorPaid(e.target.checked)}/>Assume already-due earlier statements were paid in full</label><p>These switches change eligibility; the forecast also checks the linked prior statement and the new full repayment. Actual fees, dates, eligibility and repayment rules depend on the provider. A modelled payment with insufficient cash is an unfunded obligation, not a successfully executed payment.</p><a href="https://moneysmart.gov.au/credit-cards/choosing-a-credit-card" target="_blank" rel="noreferrer">Read ASIC Moneysmart’s credit-card guidance ↗</a></details>
  <p className={s.fine}>Neither path is a recommendation. Estimates depend on the stated events, conditions and finite horizon. The fox reveals the trade-offs. You decide what matters.</p>
 </div>;
}

const engineNodes=[
 {name:'Cash truth',state:'IMPLEMENTED IN SOURCE',body:'Cash accounts, a cash-truth snapshot and protected cash distinguish what is available from what is committed. Native weekly projections use Decimal money values.'},
 {name:'Events & recurrence',state:'IMPLEMENTED IN SOURCE',body:'Entry definitions, recurring schedules and weekly indexing feed the native projection. The browser example instead uses individual dated events to expose timing between paydays.'},
 {name:'Goals & dependencies',state:'IMPLEMENTED / EXPERIMENTAL',body:'Goal ordering, due weeks and purchase spends alter projected cash. Several goal and credit-planning paths were explored; source presence does not establish financial correctness.'},
 {name:'Credit cycles',state:'EXPERIMENTAL',body:'Billing-day logic and borrow/repay entries exist. Complete lender terms, APR and grace-period eligibility are not represented. A native repayment-capacity calculation may count carried cash repeatedly.'},
 {name:'The forecast',state:'IMPLEMENTED IN SOURCE',body:'ChronoFlow’s weekly engine connects schedules, goal spends and available cash. Weekly granularity may conceal an earlier shortfall within the same week.'},
 {name:'A clearer answer',state:'VISIONARY INTERFACE',body:'A simple horizon, a useful explanation and a few what-if controls. The next-generation interface shown here is a browser concept, independent of the paused native engine.'}
];
export function EngineMap(){const [selected,setSelected]=useState(0);return <div className={s.engineMap}><p className={s.label}>INSPECT THE MACHINERY / SOURCE & VISION</p><div className={s.engineNodes}>{engineNodes.map((n,i)=><button key={n.name} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span>{String(i+1).padStart(2,'0')}</span>{n.name}<span aria-hidden="true">{i<5?'→':'↗'}</span></button>)}</div><div className={s.engineExplanation} aria-live="polite"><span>{engineNodes[selected].state}</span><h3>{engineNodes[selected].name}</h3><p>{engineNodes[selected].body}</p></div><p className={s.fine}>A conceptual dependency map, grounded in inspected source. It is not a live trace or a claim that the native financial engine is validated.</p></div>;}

const eras=[
 {title:'Traditional finance',date:'November 2025',tag:'Source-backed reconstruction',body:'A dashboard with a balance, projected cash, goal ring and optional expert detail. A familiar way to organise a growing engine.',kind:'charts'},
 {title:'A familiar home',date:'December 2025',tag:'Source-backed reconstruction',body:'A launcher of tools: cash, projections, goals and credit. Familiar mobile navigation became an experiment in reducing friction.',kind:'launcher'},
 {title:'Arrivals & departures',date:'January 2026 direction',tag:'Conceptual extension of a source-backed direction',body:'Retained source uses monospaced SAVINGS and CREDIT CARD status rows. This event timetable imagines the creator’s arrival-and-departure metaphor beyond that implementation.',kind:'airport'},
 {title:'More engine. More choices.',date:'May 2026 baseline / current working tree',tag:'Source-backed reconstruction',body:'The command surface, projections and goal flows expanded. HomeV2 and GraphV2 also contain hardcoded mock figures and incomplete actions. Capability and clarity were pulling against each other.',kind:'advanced'}
];
export function EvolutionGallery(){const [era,setEra]=useState(0);const e=eras[era];return <div className={s.gallery}><div className={s.galleryTabs} aria-label="Historical interface experiments">{eras.map((v,i)=><button aria-pressed={i===era} key={v.title} onClick={()=>setEra(i)}><span>0{i+1}</span>{v.title}</button>)}</div><div className={s.galleryContent}><div className={s.reconstruction} aria-label={`${e.title}, conceptual reconstruction, not an original screenshot`}><div className={s.mockTop}><span>CASH CAST / {e.kind==='airport'?'NEXT MONEY MOVES':'INTERFACE STUDY'}</span><small>{e.kind==='airport'?'CONCEPT EXTENSION':'RECONSTRUCTION'}</small></div>{e.kind==='charts'?<><span>Available cash</span><strong>$2,000</strong><svg viewBox="0 0 400 100" aria-hidden="true"><path d="M0 20L65 35L115 70L150 85L180 90L220 15L290 40L340 65L400 10" fill="none" stroke="#75dce4" strokeWidth="3"/></svg><div className={s.mockTiles}><span>Goal progress ◯</span><span>Optional detail ↗</span></div></>:e.kind==='launcher'?<><strong>Your next move.</strong><div className={s.launcher}>{['Cash','Projection','Goals','Credit','Reports','Settings'].map((v,i)=><div key={v}><CashIcon kind={i}/><span>{v}</span></div>)}</div></>:e.kind==='airport'?<><div className={s.boardHead}><span>DATE</span><span>EVENT</span><span>FLOW</span></div>{[['08 MAY','RENT','DEPARTURE'],['15 MAY','CARD','DEPARTURE'],['18 MAY','SALARY','ARRIVAL']].map(row=><div className={s.boardRow} key={row[1]}>{row.map(t=><span key={t}>{t}</span>)}</div>)}</>:<><strong>The question meets the engine.</strong><div className={s.mockTiles}><span>Available cash<br/>$2,000</span><span>Protected cash<br/>Commitments</span></div><div className={s.mockOrbit}><CashIcon kind={6}/><span>Goals ↔ Cash ↔ Credit</span></div></>}<p>{e.kind==='airport'?'Illustrative event board extending the documented metaphor. Not a retained implemented timetable.':'Illustrative values. Interpreted from retained interface source; never an original screenshot.'}</p></div><div><span className={s.label}>{e.date} / {e.tag}</span><h3>{e.title}</h3><p>{e.body}</p><p className={s.fine}>The creator recalls approximately twelve major iterations. Four retained source directions are shown here; the available history does not establish twelve discrete releases.</p></div></div></div>;}

export function ControllerConcept(){const [shifted,setShifted]=useState(false);const result=forecast(shifted?goalBase:baseline);return <div className={s.controllerScene}><div><p className={s.label}>NEXT-GENERATION INTERFACE / BROWSER CONCEPT</p><h3>The answer.<br/>Then the choice.</h3><p>An enormous engine can live behind one question. Show the approaching event. Explain the assumption. Let the person explore a different date.</p><p className={s.mantra}>COMPLEXITY IS OUR PROBLEM.<br/><em>SIMPLICITY IS THE USER’S RIGHT.</em></p></div><div className={s.phone}><div className={s.phoneIsland}/><Image src="/specimens/cashcast/fox-original.png" width={80} height={80} alt="Original Cash Cast neon fox"/><span className={s.label}>YOUR FINANCIAL HORIZON</span><p>Will my money last?</p><strong>{result.firstShortfall?money(result.firstShortfall.balanceCents):'A clearer path.'}</strong><p>{result.firstShortfall?`A possible shortfall on ${formatDay(result.firstShortfall.day)}.`:'No projected shortfall in this 35-day example.'}</p><small>{shifted?'Rent moves to 19 May with the mock payee’s agreement.':'The current balance is $2,000. Upcoming commitments change the picture.'}</small><button onClick={()=>setShifted(v=>!v)}>{shifted?'See the original future':'What if rent moves?'} ↗</button><a href="#origin">Explore every event</a><span className={s.fine}>Illustrative estimates · You remain in control.</span></div></div>;}

export function CashIcon({kind}:{kind:number}){const paths=['M7 28V12h26v22H7M20 6v16m-5-5 5 5 5-5','M8 6h24v30H8M14 15h12M14 22h12M14 29h8','M20 5 37 34H3L20 5Zm0 10v9m0 5v1','M5 32V14l15-8 15 8v18H5Zm8 0V20h14v12','M6 10h28v25H6M12 5v10M28 5v10M12 22h16','M6 13h28v20H6M6 20h28M11 27h6','M20 5v7M20 28v7M5 20h7M28 20h7M20 12a8 8 0 1 0 0 16 8 8 0 0 0 0-16','M5 9h12v22H5M23 9h12v22H23M17 20h6','M8 12a14 14 0 1 1-2 13M8 5v9H1','M20 5a15 15 0 1 0 15 15M20 12v10m0 6v1','M5 30 15 20l8 6 12-17M26 9h9v9'];return <svg viewBox="0 0 40 40" aria-hidden="true"><path d={paths[kind%paths.length]} fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg>;}
