import type { CashCastSpecimen, SpecimenArtwork } from './types';
const art = (name:string,alt:string):SpecimenArtwork => ({src:`/specimens/cashcast/${name}-v1.webp`,width:1536,height:1024,alt});
export const cashcast:CashCastSpecimen = {
 id:'cashcast',number:'008',slug:'cashcast',name:'CASH CAST',epithet:'See Tomorrow. Change Today.',type:'app',status:'paused',statusLabel:'Paused — Research & Development',generation:'The unfinished beginning',classification:'FINANCIAL FORESIGHT / THE FIRST SERIOUS GAMA SOFTWARE PROJECT',
 summary:'The first serious GAMA Dynamics project: a neon fox, an ambitious forecasting engine, and a simple human question — will my money last?',
 narrative:'Born from a personal need for financial foresight. Shaped by a search for simplicity. Paused as the machinery grew harder to maintain. Its philosophy remains alive.',mission:'Financial clarity without financial judgment.',platforms:['iPhone','iPad'],technologySummary:['SwiftUI / SwiftData','ChronoFlow engine experiments','Cash-flow scenarios','Local illustrative browser model'],featuredOrder:8,accent:'neon',productLink:{url:'/incubation/cashcast#origin',label:'Explore the forecast'},
 chapters:[
  {id:'origin',title:'The question',heading:'When will my money run out?',paragraphs:['A positive balance is a moment in time. Rent, bills and a salary that arrives later tell a different story. CASH CAST began with the wish to see that story early enough to change it.']},
  {id:'experiment',title:'The rebellion',heading:'Your money is not your homework.',paragraphs:['“I refuse to track every coffee.” The ambition was foresight without compulsory budgets, transaction chores or financial judgment. A navigator recalculates when life changes.']},
  {id:'system',title:'Borrowing from tomorrow',heading:'Two futures. One decision that stays yours.',paragraphs:['Waiting uses cash you have built up. Bringing a purchase forward introduces a repayment commitment. CASH CAST explored the timing between them; neither path is automatically better.']},
  {id:'problems',title:'The beast',heading:'Every simple answer hides a thousand calculations.',paragraphs:['Income meets obligations. Card cycles meet goals. One change travels through the forecast. The challenge was making the machinery capable without making the person operate it.']},
  {id:'solutions',title:'The controller',heading:'Power underneath. Simplicity on the surface.',paragraphs:['The creator’s metaphor: “A nuclear power plant operated with a PS5 controller.” A familiar handful of controls for an enormous engine. An analogy for approachability, with no affiliation to Sony or PlayStation.']},
  {id:'evolution',title:'The unfinished beginning',heading:'Paused. Not forgotten.',paragraphs:['CASH CAST was the creator’s first serious GAMA Dynamics software project. Its ambitions grew through approximately twelve major iterations, in the creator’s account. Eventually, the complexity exceeded what he could confidently maintain and simplify at that point.']}
 ],
 artwork:{hero:art('awakening','The original angular magenta-and-cyan fox is reimagined as a light sculpture above a luminous financial horizon.'),beast:art('beast','A small neon fox surveys a vast conceptual forecasting engine of timing rings and connected light paths.'),paths:art('paths','Two equally considered luminous routes lead toward the same horizon, one with a future repayment checkpoint.'),final:art('horizon','The Cash Cast neon fox overlooks a quiet luminous horizon, with unfinished structures behind it.')},
 captures:[
 {id:'calibration',src:'/specimens/cashcast/captures/calibration-current.webp',width:780,height:1696,title:'No stress. Recalibrate.',alt:'Actual Cash Cast native calibration screen showing fictional cash changing from zero to two thousand dollars and a reassuring one-time adjustment explanation.',note:'Current-source simulator · 8 October 2026. Fictional $2,000 cash adjustment; no scheduled events.'},
 {id:'launcher',src:'/specimens/cashcast/captures/launcher-current.webp',width:780,height:1696,title:'The retained command surface.',alt:'Actual current Cash Cast native launcher showing a fictional two thousand dollar cash balance and modules for projections, goals, cash, credit, records and entries.',note:'Current-source simulator · 8 October 2026. Engine-connected launcher with fictional $2,000 and an empty schedule.'}
 ],closingLines:['YOUR MONEY. YOUR DECISIONS. YOUR FUTURE.','No guilt. No homework. Just a clearer tomorrow.','SEE TOMORROW. CHANGE TODAY.']
};
