import type { ExhibitionSpecimen, SpecimenArtwork } from './types';
const art=(file:string,alt:string):SpecimenArtwork=>({src:`/specimens/gama-demo/${file}-v1.webp`,width:1536,height:1024,alt});
export const gamaDemo:ExhibitionSpecimen={
 id:'GAMA-006',number:'006',slug:'gama-demo',name:'GAMA DEMO',epithet:'The Portfolio You Can Touch',type:'demo',status:'experimental',statusLabel:'Working native showcase',generation:'Native portfolio / Internal showcase',classification:'INTERACTIVE PORTFOLIO / NATIVE EXPERIENCES',summary:'A native portfolio that opens real interactive demonstrations of GAMA applications using local sample data, so discovery begins where screenshots end.',narrative:'One device. Multiple experiences.',mission:'Let people discover the work through their own interactions.',platforms:['iPhone','iPad'],technologySummary:['SwiftUI','SwiftData','Embedded product roots','Local sample data'],featuredOrder:6,accent:'electric',productLink:{url:'/incubation/gama-demo#experiment',label:'Explore the Lobby'},closingLines:["Don’t just look at what we’ve built.",'Experience it.'],
 chapters:[
 {id:'origin',title:'Beyond the screenshot',heading:'A screenshot shows. An experience answers.',paragraphs:['A still image can reveal an interface. A film can demonstrate a sequence. Neither lets you decide what happens next.','GAMA DEMO makes the next move yours. Selected product behaviour, on a real Apple device, with example information.']},
 {id:'experiment',title:'The Lobby',heading:'One entrance. Different worlds.',paragraphs:['The Lobby is the native portfolio’s starting point: product families, platform badges and a launch button. Compact navigation on iPhone becomes a split view on iPad.']},
 {id:'system',title:'Enter the experience',heading:'The interface is only the beginning.',paragraphs:['A launch creates a session and retains the selected root. Each experience brings its own navigation and personality. End Demo returns you to the host’s Lobby.']},
 {id:'problems',title:'Simulated data',heading:'Real interaction. Example information.',paragraphs:['The point is to explore behaviour without touching a customer’s order, a family’s groceries or a running production line.']},
 {id:'solutions',title:'One portfolio',heading:'Three launches. Three personalities.',paragraphs:['A household, a boutique and a factory. Different interactions, gathered into one native portfolio.']},
 {id:'evolution',title:'The possibilities',heading:'Pick up the possibilities.',paragraphs:['The portfolio can grow through new registered product roots. Each addition needs its own honest boundary between what is demonstrated and what is still imagined.']},
 ],artwork:{hero:{...art('gateway','A tablet and three cinematic portals into a green household, coral boutique and blue factory; conceptual setting inspired by the authentic Lobby capture shown separately.'),src:'/specimens/gama-demo/gateway-v2.webp'},boundary:art('local-worlds','Three sample-data worlds inside one tablet, physically separate from a distant warehouse and records archive.'),icons:art('concept-icons','Five sculptural concepts: touch interaction, sample data blocks, separate environments, a native device and independent portals.')},
 captures:[{id:'lobby',title:'The actual Lobby',src:'/specimens/gama-demo/captures/lobby.webp',width:1350,height:1800,alt:'Authentic GAMA DEMO iPad Lobby with platform filters, product cards and launch controls.',note:'Native iPad simulator capture · 8 Oct 2026. Includes explicit placeholder entries.'},{id:'phoenix',title:'Grocery Master Phoenix',src:'/specimens/gama-demo/captures/phoenix.webp',width:1350,height:1800,alt:'Authentic seeded Phoenix household with Living List, shop filters, pantry and shopping mode.',note:'Native demo capture · fictional seeded household. A separate Phoenix showcase, not the approved Specimen 001 app.'},{id:'coco',title:'Coco the Llama',src:'/specimens/gama-demo/captures/coco.webp',width:1350,height:1800,alt:'Authentic Coco customer demo with four shopping entry points and native tabs.',note:'Native demo capture · local catalogue and basket. No live order placed.'},{id:'wayline',title:'WAYLINE',src:'/specimens/gama-demo/captures/wayline.webp',width:1350,height:1800,alt:'Authentic WAYLINE native factory scenario showing six stages with PRE, ACTIVE and POST zones.',note:'Native iPad demo capture · deterministic scenario and authored data.'}]
};
