import type { ExhibitionSpecimen, SpecimenArtwork } from './types';
const art=(file:string,alt:string):SpecimenArtwork=>({src:`/specimens/wayline/${file}-v1.webp`,width:1536,height:1024,alt});
export const wayline:ExhibitionSpecimen={
 id:'GAMA-007',number:'007',slug:'wayline',name:'WAYLINE',epithet:'Every Item. Every Stage. Every Second.',type:'experiment',status:'experimental',statusLabel:'Prototype + future vision',generation:'Industrial flow / Evolving concept',classification:'PRODUCTION FLOW / ITEM JOURNEYS',summary:'An evolving industrial flow concept that follows individual items through processing, waiting and completion, making the time between stations visible.',narrative:'Your factory knows how to produce. WAYLINE shows you where time disappears.',mission:'Make the journey of every item understandable.',platforms:['iPad prototype','Conceptual browser simulation'],technologySummary:['SwiftUI prototype','Timestamped journeys','Deterministic simulation','Interactive browser model'],featuredOrder:7,accent:'titanium',productLink:{url:'/incubation/wayline#problems',label:'Run the factory'},closingLines:['Your factory knows how to produce.','WAYLINE shows you where time disappears.'],
 chapters:[
 {id:'origin',title:'The Swiss watch',heading:'Perfect rhythm. Imperfect reality.',paragraphs:['A watch turns in exquisite coordination. A factory aspires to the same rhythm, with people, maintenance, late materials and changing process times in the middle.','WAYLINE begins with the interruption. Follow the item, and the rhythm becomes visible.']},
 {id:'experiment',title:'The item’s journey',heading:'The item is the thread.',paragraphs:['Where is it? What has it completed? How long did it work, and how long did it wait? One identity connects every stage of the journey.']},
 {id:'system',title:'Where time disappears',heading:'Waiting is part of the story.',paragraphs:['A machine can be busy while an item is still. Active time and waiting time need different measurements, different signals and the same clear timeline.']},
 {id:'problems',title:'The bottleneck',heading:'One interruption. A different factory.',paragraphs:['Slow one stage. Watch the queue form. Restore the rhythm and see the backlog clear through real processing, one item at a time.']},
 {id:'solutions',title:'The factory in your hands',heading:'An entire operation. Within reach.',paragraphs:['The item reveals the journey. The station reveals the constraint. The manager sees how they connect.']},
 {id:'evolution',title:'The future of flow',heading:'What if the line could explain itself?',paragraphs:['The prototype is a starting point. The vision reaches toward playback, scenario planning and earlier understanding of developing constraints.']},
 ],artwork:{hero:art('watch-to-factory','Precision Swiss watch gears transition into a PVD coating facility, linked by a cyan production route.'),manager:art('manager','A production manager holds a landscape iPad with a conceptual WAYLINE operations dashboard in a modern factory.'),pills:art('living-items','Conceptual capsules move through a titanium production line, with an amber queue before coating.'),icons:art('concept-icons','Sculptural concepts for processing, waiting, queue order, capacity, throughput, timing, delays and flow.')},
 captures:[{id:'prototype',title:'The existing iPad prototype',src:'/specimens/wayline/captures/native-flow.webp',width:1350,height:1800,alt:'Authentic WAYLINE iPad prototype with Picking, Racking, Washing, Coating, De-racking and Finishing stages.',note:'Native prototype · local deterministic scenario. PRE / ACTIVE / POST zones and stable trolley identifiers.'}]
};
