'use client';
import { useState } from 'react';
import Image from 'next/image';
import s from './DemoExplorer.module.css';
const products = [
  {id:'phoenix',name:'Grocery Master Phoenix',family:'Consumer',platforms:['iPhone','iPad'],color:'#b6e2a3',image:'phoenix',description:'A seeded household. A Living List. The rhythm of a real shop.',features:['Add and check items','Adjust quantities','Filter by shop','Explore pantry and shopping mode']},
  {id:'coco',name:'Coco the Llama',family:'Retail',platforms:['iPhone','iPad'],color:'#f0b8ac',image:'coco',description:'Four ways to shop, with a local catalogue, picks and basket.',features:['Explore shopping personas','Browse seeded products','Choose sizes and quantities','Build a local basket']},
  {id:'wayline',name:'WAYLINE',family:'Operations',platforms:['iPad'],color:'#9bdfe6',image:'wayline',description:'Follow a trolley through a deterministic factory scenario.',features:['Build a workflow','Inspect trolley journeys','Replay sample history','Explore authored insights']},
];
export default function DemoExplorer(){
 const [family,setFamily]=useState('All');const [platform,setPlatform]=useState('All');const [launched,setLaunched]=useState<string|null>(null);const [items,setItems]=useState([{id:1,name:'Sourdough',done:false},{id:2,name:'Avocados',done:false},{id:3,name:'Oat milk',done:false}]);const [newItem,setNewItem]=useState('');const [message,setMessage]=useState('');
 const product=products.find(p=>p.id===launched);
 const filtered=products.filter(p=>(family==='All'||p.family===family)&&(platform==='All'||p.platforms.includes(platform)));
 return <div className={s.explorer}>
 <div className={s.top}><div><span>AN INTERACTIVE BROWSER COMPANION</span><h3>{product?product.name:'Choose your world.'}</h3></div>{product&&<button onClick={()=>{setLaunched(null);setMessage('Returned to the browser Lobby.');}}>← End browser demo</button>}</div>
 <p className={s.note}>Source-grounded browser excerpts. The native SwiftUI application is shown in the authentic captures below; it is not running inside this page.</p>
 {!product?<><div className={s.filters}><label>Product family<select aria-label="Product family" value={family} onChange={e=>setFamily(e.target.value)}>{['All','Consumer','Retail','Operations'].map(f=><option key={f}>{f}</option>)}</select></label><label>Platform<select aria-label="Platform" value={platform} onChange={e=>setPlatform(e.target.value)}>{['All','iPhone','iPad'].map(f=><option key={f}>{f}</option>)}</select></label><span>{filtered.length} substantive {filtered.length===1?'experience':'experiences'}</span></div><div className={s.cards}>{filtered.map(p=><article key={p.id} style={{borderColor:p.color}}><span className={s.world} style={{color:p.color}}>{p.family} / {p.platforms.join(' + ')}</span><h4>{p.name}</h4><p>{p.description}</p><button onClick={()=>{setLaunched(p.id);setMessage(`${p.name} browser excerpt opened.`);}}>Enter experience ↗</button></article>)}</div><p className={s.note}>Verified substantive launches: three. The native catalogue also contains six placeholder experiences, which are not presented here as finished products.</p></>:
 <div className={s.launched}><div className={s.interaction}>
 {product.id==='phoenix'?<><span className={s.world}>LOCAL EXAMPLE / LIVING LIST</span><h4>Make the list yours.</h4><p>Check an item. Add something. The state changes here in your browser.</p><ul>{items.map(i=><li key={i.id}><label><input type="checkbox" checked={i.done} onChange={()=>setItems(all=>all.map(x=>x.id===i.id?{...x,done:!x.done}:x))}/><span style={{textDecoration:i.done?'line-through':'none'}}>{i.name}</span></label></li>)}</ul><form onSubmit={e=>{e.preventDefault();const name=newItem.trim();if(!name){setMessage('Enter an item name.');return;}if(items.some(i=>!i.done&&i.name.toLowerCase()===name.toLowerCase())){setMessage('That item is already on the active list.');return;}setItems(all=>[...all,{id:Math.max(...all.map(i=>i.id))+1,name,done:false}]);setNewItem('');setMessage(`${name} added to this local example.`);}}><label htmlFor="demo-grocery-item">Add an item</label><div><input id="demo-grocery-item" value={newItem} onChange={e=>setNewItem(e.target.value)} maxLength={60} placeholder="e.g. Apples"/><button>Add</button></div></form><p>{items.filter(i=>!i.done).length} to find · no production connection</p></>:<><span className={s.world}>VERIFIED NATIVE INTERACTIONS</span><h4>{product.description}</h4><ul>{product.features.map(f=><li key={f}>↗ {f}</li>)}</ul>{product.id==='wayline'?<a href="/incubation/wayline#problems">Try the conceptual factory simulation →</a>:<p>Explore the authentic native capture alongside. This excerpt does not place orders or connect to the live shop.</p>}</>}
 </div><figure><Image src={`/specimens/gama-demo/captures/${product.image}.webp`} alt={`Authentic ${product.name} native demo screenshot`} width={2064} height={2752}/><figcaption>Authentic native capture · iPad simulator · 8 Oct 2026 · sample data</figcaption></figure></div>}
 <p className={s.status} role="status">{message}</p></div>;
}
export function ScreenshotComparison(){const[mode,setMode]=useState<'image'|'touch'>('image');const[count,setCount]=useState(0);return <div className={s.comparison}><div><button aria-pressed={mode==='image'} onClick={()=>setMode('image')}>Look at it</button><button aria-pressed={mode==='touch'} onClick={()=>setMode('touch')}>Interact with it</button></div><div className={s.sample}><span>ILLUSTRATIVE BROWSER INTERACTION</span><strong>One small action.<br/>A different understanding.</strong><button disabled={mode==='image'} onClick={()=>setCount(n=>n+1)} aria-label="Try the interaction">{mode==='image'?'A screenshot cannot respond.':`Touch to discover · ${count}`}</button><p role="status">{mode==='image'?'The interface is visible. The experience is still out of reach.':count?'You changed the state. That is the difference.':'Now the next move belongs to you.'}</p></div></div>;}
